#Application Url
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Login Credentials	
username=Admin
password=admin123

#browser configuration
browser=chrome

#ImplicitWwait (in seconds)
implicitWait=10

#Explicit Wait
explicitWait=30
